name: CI Build
on:
  [workflow_dispatch]
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./ -t  ${{ secrets.DOCKERHUB_USERNAME }}/accounts:0.1
      - name: push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/accounts:0.1
